classDiagram
    class Estudiante {
        +id: int
        +nombre: string
        +correo: string
        +edad: int
        +crear(): void
        +leer(): void
        +actualizar(): void
        +eliminar(): void
    }
    class Profesor {
        +id: int
        +nombre: string
        +especialidad: string
        +crear(): void
        +leer(): void
        +actualizar(): void
        +eliminar(): void
    }
    class Curso {
        +id: int
        +nombre: string
        +duracion: int
        +profesor: string
        +crear(): void
        +leer(): void
        +actualizar(): void
        +eliminar(): void
    }
    class Registro {
        +id: int
        +id_usuario: int
        +id_curso: int
        +fecha_registro: date
        +registrar(): void
    }
    
    Estudiante --> Registro : registra (1..*)
    Registro --> Curso : asocia (*..1)
    Profesor --> Registro : gestiona (1..*)
    Profesor --> Curso : imparte (1..*)